# Generated by Django 3.1.7 on 2021-04-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_article_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_author',
        ),
    ]
