# Generated by Django 3.1.7 on 2021-04-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210403_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_author',
            field=models.CharField(default='anonymus user', max_length=200, verbose_name='article author'),
        ),
    ]
