# Generated by Django 3.1.7 on 2021-04-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210406_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_author',
        ),
    ]
