# Generated by Django 3.1.7 on 2021-04-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_remove_article_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_author',
            field=models.CharField(default='anonymus user', max_length=200, verbose_name='article author'),
        ),
    ]
